CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  registration_date TIMESTAMP,
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
   id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
   user_id BIGINT,
   name VARCHAR(255) NOT NULL,
   description VARCHAR NOT NULL,
   url VARCHAR(1000),
   available BOOLEAN NOT NULL,
   CONSTRAINT fk_items_to_users FOREIGN KEY(user_id) REFERENCES users(id),
   UNIQUE(id, url)
);